version: "3.9"
# mysql -u root --password="0passlla07" --execute="show master status;"
volumes:
  db_data:
  
services:
    website:
        container_name: eduweb
        build:
            context:  .
            dockerfile: Dockerfile
        restart: unless-stopped
        image: eduweb:latest
        ports:
        - 3000
        volumes:
        - /home/beznet/website:/var/www/html/website:rw
    
    nginx:
        image: nginx:alpine
        container_name: eduweb-server
        restart: unless-stopped
        ports:
        - 8000:80
        volumes:
        - ./:/var/www
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf